### ISSUE TITLE
Plugin is ignoring rhythm samples given to it

### ISSUE THREAD

**Issue by Nephrite-FM** [stuerp/foo_input_pmd#3]
The Readme.md page doesn't mention what file format, file name or file type is expected for the 2608 rhythm samples.  From the OPNA.cpp file I can clearly infer it looks for files 2608_bd.wav, 2608_tom.wav, 2608_top.wav but I can easily prove by setting all the files to hold the same sample that the plugin is not using them properly.

It was generating rhythm without the existence of any wave files present at all...  Is there a fix coming that will override the rhythm samples internal to the plugin?  Because they do not sound right.

**Comment by stuerp** [comment]
The driver falls back to generating drum sounds using the RSS (Rhythm Sound Source). You can find the samples [here](http://snesmusic.org/hoot/drum_samples.zip). They're in RIFF WAVE format. I'll add a note in the README but it's not meant to replace all the PMD documentation that is out there.

**Comment by Nephrite-FM** [comment]
I see the files for the HOOT Player are 44.1kHz, whereas the ones I had were 48kHz, however this didn't fix anything...  These new WAV files are still not being read from.

**Comment by stuerp** [comment]
Can you upload your files or add a link? I'll have a look at them.

**Comment by Nephrite-FM** [comment]
http://snesmusic.org/hoot/drum_samples.zip

I am using the files from the link you posted...

**Comment by stuerp** [comment]
The PCM samples should be in the 1 channel, 44.1kHz and 16-bit, as are the ones in the link.

I dove deeper into this issue. I'm absolutely sure the files get loaded (confirmed in the debugger) but while reading up on percussion in PMD I found out that there are several ways a song can request percussion: PCM samples using 3 different cores, a bank in ROM or samples used by the Rhythm sound source or emulated by an effect of the SSG.

The PMD driver currently uses a number of hard-coded defaults that determine the method that will be used; hence the various options in PMDWin f.e. to tweak the behavior.

Can you provide a link to the song that sounds weird to you?

**Comment by Nephrite-FM** [comment]
I just tried out your new version, and it actually calls the Wave files into memory and plays them back now, however it is distorting the playback as they come out.  

Find attached an M file I have been using that plays 8 cymbals in a row.  The Cymbal is the best sample that exhibits this distortion.  What happens is that, no matter what the sample rate of the cymbal played, be it 44.8kHz like mine were or 44.1kHz from the HOOT Player link you provided, the pitch of the wave file is distorted exactly the same.

I even tried replacing the drum sample with a different wave file (using the Windows Ding sound sample) and it is distorted in the exact same manner through your plugin, whether or not I use the 44.1kHz Mono file of the 8khz Mono file.  The Quality drops, obviously but the pitch change between the 44.1kHz Version and the 8kHz version is identical.  It is somehow playing the WAV files back at too high a pitch, and it has nothing to do with the sample rate...  although replacing the cymbal (2608_TOP.WAV) with the Windows ding sound proves now that your version v0.4.0.0 is actually reading and playing back the samples now, just not faithfully.
[issue3.zip](https://github.com/stuerp/foo_input_pmd/files/12841625/issue3.zip)

**Comment by stuerp** [comment]
I listened to the samples (thank you) and I understand (and hear) what you mean. Both 98FMPlayer and PMDWin seem to produce the sample with the sample pitch as your recording. Must be something I broke during the conversion. I did rewrite the sample loading routines early on because they were, well, not very robust. I'll start looking there.

**Comment by stuerp** [comment]
Initializing the OPNA with another synthesis frequency seems to fix it. I don't yet understand why but can you give the attached version a test run? Only 64-bit for now.
[foo_input_pmd.zip](https://github.com/stuerp/foo_input_pmd/files/12999020/foo_input_pmd.zip)

**Comment by Nephrite-FM** [comment]
Much better!  Sounds a great deal more accurate now, all the samples are at the right pitch.

**Comment by Nephrite-FM** [comment]
Much better!  Sounds a great deal more accurate now, all the samples are at the right pitch.
